#ifndef MAIN_HPP
#define MAIN_HPP
#include <iostream>
#include <string>
#include <algorithm>
#include <memory>
#include <cassert>
#include <limits>
#include <string.h>
#include <map>
#include <vector>
#include <stack>
#include "Lexicographic.hpp"
#include "Meta.hpp"
#include "Map.hpp"
#include "Vector.hpp"
#include "Stack.hpp"
int main_ft();
int main_stl();
#endif
